 spcname |              object_name              
---------+---------------------------------------
 ygl69   | _pg_foreign_data_wrappers
 ygl69   | _pg_foreign_servers
 ygl69   | _pg_foreign_table_columns
 ygl69   | _pg_foreign_tables
 ygl69   | _pg_user_mappings
 ygl69   | administrable_role_authorizations
 ygl69   | applicable_roles
 ygl69   | attributes
 ygl69   | character_sets
 ygl69   | check_constraint_routine_usage
 ygl69   | check_constraints
 ygl69   | collation_character_set_applicability
 ygl69   | collations
 ygl69   | column_column_usage
 ygl69   | column_domain_usage
 ygl69   | column_options
 ygl69   | column_privileges
 ygl69   | column_udt_usage
 ygl69   | columns
 ygl69   | constraint_column_usage
 ygl69   | constraint_table_usage
 ygl69   | data_type_privileges
 ygl69   | domain_constraints
 ygl69   | domain_udt_usage
 ygl69   | domains
 ygl69   | element_types
 ygl69   | enabled_roles
 ygl69   | foreign_data_wrapper_options
 ygl69   | foreign_data_wrappers
 ygl69   | foreign_server_options
 ygl69   | foreign_servers
 ygl69   | foreign_table_options
 ygl69   | foreign_tables
 ygl69   | information_schema_catalog_name
 ygl69   | key_column_usage
 ygl69   | parameters
 ygl69   | referential_constraints
 ygl69   | role_column_grants
 ygl69   | role_routine_grants
 ygl69   | role_table_grants
 ygl69   | role_udt_grants
 ygl69   | role_usage_grants
 ygl69   | routine_column_usage
 ygl69   | routine_privileges
 ygl69   | routine_routine_usage
 ygl69   | routine_sequence_usage
 ygl69   | routine_table_usage
 ygl69   | routines
 ygl69   | schemata
 ygl69   | sequences
 ygl69   | sql_features
 ygl69   | sql_implementation_info
 ygl69   | sql_parts
 ygl69   | sql_sizing
 ygl69   | table_constraints
 ygl69   | table_privileges
 ygl69   | tables
 ygl69   | transforms
 ygl69   | triggered_update_columns
 ygl69   | triggers
 ygl69   | udt_privileges
 ygl69   | usage_privileges
 ygl69   | user_defined_types
 ygl69   | user_mapping_options
 ygl69   | user_mappings
 ygl69   | view_column_usage
 ygl69   | view_routine_usage
 ygl69   | view_table_usage
 ygl69   | views
 ygl69   | lake
 ygl69   | lake_id_seq
 ygl69   | lake_pkey